### ISSUE TITLE
Details of the ProCSnumpyfiles

### ISSUE THREAD

**Issue by makki547** [jensengroup/procs15#2]
Could you please provide the details of the ProCSnumpyfiles? I need to understand which axes of the .npy files correspond to the parameters.

I attempted to run ProCS15 but encountered compiling errors with PHAISTOS. Therefore, I am considering creating a Python clone that does not depend on PHAISTOS.

**Comment by larsbratholm** [comment]
The numpy files have shape (3, 361, 361, ...) where the second axis is phi, third axis is psi, and last axes are chi angles. First axis are the residues in the tripeptide (preceding, central and following). The angle count start at -180 degrees, so a backbone angle of 90 degree would be index 270. The first and last angle index both correspond to -180 degrees.
